### ISSUE TITLE
application crash inside curl_multi_perform 

### ISSUE THREAD

**Issue by sandeepReddyG** [bbc/gst-curlhttpsrc#2]
My application crashing randomly inside gst_curl_http_src_curl_multi_loop on curl_multi_perform. I have seen some posts on curl_multi_perform crash ,but I didn't find any clue to fix it. The backtrace shows different apis inside curl_multi_perform .Its not always multi_runsingle.
Here is the backtrace:
#0  0xb6518aa4 in multi_runsingle () from /usr/lib/libcurl.so.4
#1  0xb6519c00 in curl_multi_perform () from /usr/lib/libcurl.so.4
#2  0x953a739c in gst_curl_http_src_curl_multi_loop (thread_data=0xb4b21e88) at gstcurlhttpsrc.c:1604
#3  0xb6b52868 in gst_task_func (task=0x3e62c8) at gsttask.c:332
#4  0xb69e2c30 in g_thread_pool_thread_proxy () from /usr/lib/libglib-2.0.so.0
#5  0xb69e23d0 in g_thread_proxy () from /usr/lib/libglib-2.0.so.0
#6  0xb6bc45d8 in start_thread (arg=0x0) at pthread_create.c:335
#7  0xb66f7102 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:86 from /lib/libc.so.6

**Comment by samhurst** [comment]
Hi,

Are you using the version of curlhttpsrc that's in gst-plugins-bad, or have you built it yourself from git? We're not really maintaining it here anymore, since it has been accepted into the GStreamer source tree and there has been more work done on it there, independently of this repository. If you're having issues with the version in gst-plugins-bad, you could try raising an issue on the [GStreamer GitLab issue tracker](https://gitlab.freedesktop.org/gstreamer).

-Sam
